### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by thisguy23** [Gilzy/403Bypasser#1]
Watching the requests in Logger after manual activation, it doesn't seem to attempt adding the headers.

Maybe I'm missing something.

**Comment by Gilzy** [comment]
The extension is built in such a way that it would only look for header-based bypasses if there aren't any query-based ones.
This can be easily changed however in future updates if there's a demand for it.

**Comment by Gilzy** [comment]
This has been fixed [here](https://github.com/Gilzy/403Bypasser/commit/d5f434a1ad9e540d205eb6ff2e731cc1b45775d8)
